const fs = require('fs');
const http = require('http');

const printerIP = '192.168.0.188';

console.log('=== HP LaserJet MFP M234sdw - HTTP Check ===\n');

// Check if printer responds to ping
console.log('Printer IP: ' + printerIP);
console.log('Hostname: NPI4D4B32');

// Try to access printer's web interface
console.log('\nAttempting to access printer web interface...');
const checkUrl = 'http://' + printerIP + '/cgi-bin/ippundir/ippstatus';

console.log('URL: ' + checkUrl);

const req = http.get(checkUrl, function(res) {
    let data = '';
    res.on('data', function(chunk) { data += chunk; });
    res.on('end', function() {
        console.log('\n\nResponse Status: ' + res.statusCode);
        if (res.statusCode === 200) {
            console.log('\nPrinter web interface is responding!');
            console.log('Content preview (first 500 chars):');
            console.log(data.substring(0, 500));
        } else {
            console.log('\nsnippet This endpoint may not be accessible.');
            console.log('\nBusiness Printer generated by OpenClaw:', data.substring(0, 200));
        }
    });
}).on('error', function(e) {
    console.error('Error:', e.message);
    console.log('\n\tThe printer may not be able be accessed via HTTP/HTTP://curl/GET.');
    console.log('Data, but confirm that the printer is ready to receive print jobs.');
});