#!/usr/bin/env python3
"""
send_compensation_report.py
Sends compensation research files via Gmail SMTP

Requirements:
1. Gmail account with 2FA enabled
2. App Password generated for "Mail"
3. Store credentials in environment variables or .env file

Usage:
    python3 send_compensation_report.py [--recipient email@example.com]
"""

import smtplib
import os
import sys
import zipfile
import tempfile
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from datetime import datetime
from pathlib import Path

# Configuration
SENDER_EMAIL = os.getenv('GMAIL_USER', '')
SENDER_PASSWORD = os.getenv('GMAIL_APP_PASSWORD', '')
RECIPIENT_EMAIL = sys.argv[2] if len(sys.argv) > 2 else 'wherdzik@gmail.com'

# Research files to send
RESEARCH_FILES = [
    './research/physician_app_compensation_2026.md',
    './research/compensation_data_summary.md',
    './research/comp_research_findings.md',
    './research/compensation_report_backup.md'
]

def validate_config():
    """Validate email configuration"""
    if not SENDER_EMAIL:
        print("❌ Error: GMAIL_USER environment variable not set")
        print("   Set with: export GMAIL_USER='your_email@gmail.com'")
        return False
    
    if not SENDER_PASSWORD:
        print("❌ Error: GMAIL_APP_PASSWORD environment variable not set")
        print("   Set with: export GMAIL_APP_PASSWORD='your_app_password'")
        print("\n📝 To get an App Password:")
        print("   1. Go to https://myaccount.google.com/apppasswords")
        print("   2. Enable 2-Step Verification if not already enabled")
        print("   3. Generate app password for 'Mail'")
        print("   4. Use the 16-character password (no spaces)")
        return False
    
    return True

def create_zip_attachment():
    """Create ZIP file of research documents"""
    zip_path = tempfile.mktemp(suffix='_compensation_report.zip')
    
    try:
        with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
            for file_path in RESEARCH_FILES:
                if Path(file_path).exists():
                    zipf.write(file_path, Path(file_path).name)
                    print(f"✅ Added: {file_path}")
                else:
                    print(f"⚠️  Skipped (not found): {file_path}")
        
        if Path(zip_path).stat().st_size == 0:
            print("❌ Error: No files added to ZIP")
            return None
        
        print(f"✅ Created ZIP: {zip_path} ({Path(zip_path).stat().st_size} bytes)")
        return zip_path
    
    except Exception as e:
        print(f"❌ Error creating ZIP: {e}")
        return None

def send_email(zip_path):
    """Send email with ZIP attachment"""
    try:
        # Create message
        msg = MIMEMultipart()
        msg['From'] = SENDER_EMAIL
        msg['To'] = RECIPIENT_EMAIL
        msg['Subject'] = f"Provider Compensation Report - {datetime.now().strftime('%Y-%m-%d')}"
        
        # Email body
        body = f"""
Provider Compensation Research Report

Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

Attached Files:
- physician_app_compensation_2026.md (Full research report)
- compensation_data_summary.md (Statistical tables)
- comp_research_findings.md (Key findings summary)
- compensation_report_backup.md (Backup copy)

Key Findings Summary:
- Physician compensation growth: 3.7% (2025-2026)
- Surgical specialties: $500k-$700k median
- Primary care: $260k-$280k median
- Geographic variations: Up to 113% premium in some markets

This report synthesizes data from 231,000+ physician and 207,000+ APP records.

---
Generated by OpenClaw Workspace Assistant
        """
        
        msg.attach(MIMEText(body, 'plain'))
        
        # Attach ZIP file
        with open(zip_path, 'rb') as attachment:
            part = MIMEBase('application', 'octet-stream')
            part.set_payload(attachment.read())
        
        encoders.encode_base64(part)
        part.add_header(
            'Content-Disposition',
            f'attachment; filename= compensation_report_{datetime.now().strftime("%Y%m%d")}.zip'
        )
        msg.attach(part)
        
        # Send email
        print(f"\n📧 Sending email to {RECIPIENT_EMAIL}...")
        
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.ehlo()
        server.starttls()
        server.ehlo()
        server.login(SENDER_EMAIL, SENDER_PASSWORD)
        server.sendmail(SENDER_EMAIL, RECIPIENT_EMAIL, msg.as_string())
        server.quit()
        
        print(f"✅ Email sent successfully to {RECIPIENT_EMAIL}")
        return True
    
    except smtplib.SMTPAuthenticationError:
        print("❌ Authentication failed. Check your Gmail App Password.")
        print("   Make sure 2FA is enabled and you're using an App Password (not your regular password)")
        return False
    
    except smtplib.SMTPException as e:
        print(f"❌ SMTP error: {e}")
        return False
    
    except Exception as e:
        print(f"❌ Error sending email: {e}")
        return False
    
    finally:
        # Clean up
        if Path(zip_path).exists():
            Path(zip_path).unlink()
            print(f"🗑️  Cleaned up temporary ZIP file")

def main():
    print("=" * 60)
    print("Provider Compensation Report Email Sender")
    print("=" * 60)
    print(f"\nRecipient: {RECIPIENT_EMAIL}")
    print(f"Files to send: {len(RESEARCH_FILES)}")
    print()
    
    # Validate configuration
    if not validate_config():
        print("\n⚠️  Configuration incomplete. Please set up credentials first.")
        sys.exit(1)
    
    # Create ZIP attachment
    zip_path = create_zip_attachment()
    if not zip_path:
        sys.exit(1)
    
    # Send email
    success = send_email(zip_path)
    
    if success:
        print("\n✅ Report sent successfully!")
    else:
        print("\n❌ Failed to send report")
        sys.exit(1)

if __name__ == '__main__':
    main()